// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQsrWgBt24IF0OamMlYv8_gqsvF7_TPDQ',
    appId: '1:338506223143:web:7c2a5b936e8fdb6f0d4802',
    messagingSenderId: '338506223143',
    projectId: 'idealab-backend-985ef',
    authDomain: 'idealab-backend-985ef.firebaseapp.com',
    storageBucket: 'idealab-backend-985ef.firebasestorage.app',
    measurementId: 'G-ZL00KLXSXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9c1hpIgZO729Qvi4sagJdBBiEKiyx_M',
    appId: '1:338506223143:android:1179e7f4e21ec8500d4802',
    messagingSenderId: '338506223143',
    projectId: 'idealab-backend-985ef',
    storageBucket: 'idealab-backend-985ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSItFs807WNkj_Hj-bZVxYGr8ZwdpUsao',
    appId: '1:338506223143:ios:f9200a638ec70fbd0d4802',
    messagingSenderId: '338506223143',
    projectId: 'idealab-backend-985ef',
    storageBucket: 'idealab-backend-985ef.firebasestorage.app',
    iosClientId: '338506223143-bk8e2k86nrdi1246uv8rob3fhppmj218.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSItFs807WNkj_Hj-bZVxYGr8ZwdpUsao',
    appId: '1:338506223143:ios:f9200a638ec70fbd0d4802',
    messagingSenderId: '338506223143',
    projectId: 'idealab-backend-985ef',
    storageBucket: 'idealab-backend-985ef.firebasestorage.app',
    iosClientId: '338506223143-bk8e2k86nrdi1246uv8rob3fhppmj218.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQsrWgBt24IF0OamMlYv8_gqsvF7_TPDQ',
    appId: '1:338506223143:web:4a432bd6d6e29efc0d4802',
    messagingSenderId: '338506223143',
    projectId: 'idealab-backend-985ef',
    authDomain: 'idealab-backend-985ef.firebaseapp.com',
    storageBucket: 'idealab-backend-985ef.firebasestorage.app',
    measurementId: 'G-33TCKD663Z',
  );
}