// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuavbVx5NDmicTuABwsPNBm-3vGH3ntOA',
    appId: '1:94074972466:web:2661c380febc9cf2b94f2b',
    messagingSenderId: '94074972466',
    projectId: 'idealab-001',
    authDomain: 'idealab-001.firebaseapp.com',
    storageBucket: 'idealab-001.firebasestorage.app',
    measurementId: 'G-012ZMQGFX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBnzJE_V89xd1as2avbVpQ9OB8Uukjeg',
    appId: '1:94074972466:android:576b3f0344284e99b94f2b',
    messagingSenderId: '94074972466',
    projectId: 'idealab-001',
    storageBucket: 'idealab-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpGHV-9-_u_B5F6xnMrk0fO8_lUq8ZFU',
    appId: '1:94074972466:ios:f01a41e9a77d8446b94f2b',
    messagingSenderId: '94074972466',
    projectId: 'idealab-001',
    storageBucket: 'idealab-001.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVpGHV-9-_u_B5F6xnMrk0fO8_lUq8ZFU',
    appId: '1:94074972466:ios:f01a41e9a77d8446b94f2b',
    messagingSenderId: '94074972466',
    projectId: 'idealab-001',
    storageBucket: 'idealab-001.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuavbVx5NDmicTuABwsPNBm-3vGH3ntOA',
    appId: '1:94074972466:web:b9db7c65974571fdb94f2b',
    messagingSenderId: '94074972466',
    projectId: 'idealab-001',
    authDomain: 'idealab-001.firebaseapp.com',
    storageBucket: 'idealab-001.firebasestorage.app',
    measurementId: 'G-ZCQYR7365P',
  );
}
